name: Build Alfio

on: push

jobs:

  container-job:
    runs-on: macos-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        run: node client.js

        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

      - name: Check out Alfio code
        uses: actions/checkout@v4
        with:
          repository: 'hongsim-tran/alf.io'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Gradle build
        run: ./gradlew clean

      - name: Alfio build
        run: ./gradlew -Pprofile=dev :bootRun



